#document settings
title: Project Interoperability (IDA Hybrid Demo)
desc: "Project Interoperability (IDA Hybrid Demo): The GitHub Portion"
url: /project-interoperability.github.io/
repo_name: project-interoperability.github.io
branch: gh-pages
secure: optional

#global settings, no need to change these
root_url: http://ida-org.github.io/project-interoperability.github.io/
org_name: ida-org
prose_url: http://prose.io

# default build settings for running locally, no need to edit
pymgemnts: true
exclude: ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md"]
markdown: kramdown
relative_permalinks: false
